version: '3'
services:
        web:
                image: art_port_1
                build: .
                ports:
                        - "8794:8794"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
